name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '1.8'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v3
      with:
        api-levels: 26
        target: google_apis
        arch: x86
        force-avd-creation: true
        emulators: 'Pixel_2_API_26'
        script: ./gradlew build

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
